course=("  python programming")
print(len(course))
print(type(course))
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.count("o"))
print(course.replace("p","j"))